Repository projectsyn/component-thanos, pull requests merged in 2021-11, with the labels that each got.

#12 Prepare for modulesync-control
  .sync.yml
Labels: change

#15 Add logic to ensure stable Jsonnet dependencies on OCP4
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  jsonnetfile.jsonnet
Labels: enhancement

#17 Add parameter to allow disabling query component
  class/defaults.yml
  component/query.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement

#16 Properly configure querier stores
  component/query.libsonnet
  tests/golden/defaults/thanos/thanos/query/deployment.yaml
Labels: change

#13 Add support for multiple instances
  .github/workflows/test.yaml
  .sync.yml
  class/defaults.yml
  class/thanos.yml
  component/app.jsonnet
  component/dashboards.libsonnet
  docs/modules/ROOT/pages/how-tos/multi-instance.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/store/thanos/apps/thanos.yaml
  tests/golden/store/thanos/thanos/00_namespace.yaml
  tests/golden/store/thanos/thanos/40_thanos_objstore.yaml
  tests/golden/store/thanos/thanos/bucket/deployment.yaml
  tests/golden/store/thanos/thanos/bucket/service.yaml
  tests/golden/store/thanos/thanos/bucket/serviceAccount.yaml
  tests/golden/store/thanos/thanos/store/alerts.yaml
  tests/golden/store/thanos/thanos/store/service.yaml
  tests/golden/store/thanos/thanos/store/serviceAccount.yaml
  tests/golden/store/thanos/thanos/store/serviceMonitor.yaml
  tests/golden/store/thanos/thanos/store/statefulSet.yaml
  tests/store.yml
Labels: enhancement

#10 Add support for deploying Thanos Receiver
  class/defaults.yml
  component/main.jsonnet
  component/query.libsonnet
  component/receive.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement

#18 Add parameter to disable creation of namespaces
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/how-tos/multi-instance.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/store/thanos/thanos/00_namespace.yaml
  tests/store.yml
Labels: bug
